<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b8e55883-b519-46ff-85fa-3a7d096aaa8b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_blockchain</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[1]/nav[1]/span[1]/span[1]/ol[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex\ items-center"]:nth-child(2) &gt; [class="rounded\ px-1\ text-sm\ font-medium\ ring-inset\ ring-blue-300\ hover\:text-blue-500\ focus-visible\:text-blue-500\ focus-visible\:ring\ active\:text-blue-700\ dark\:ring-blue-300\ dark\:hover\:text-blue-400\ dark\:focus-visible\:text-blue-400\ dark\:active\:text-blue-600\ text-gray-400\ dark\:text-zinc-500"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Blockchain')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Blockchain</value>
        <webElementGuid>c3e9a72f-a461-4000-8112-6005055d39a5</webElementGuid>
    </webElementProperties>
</WebElementEntity>