<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3668f080-566a-4d13-9e33-14bee92aa5a1</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nft</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[3]/li[1]/ul[1]/li[5]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="pl-8\ py-1\ pr-1"] &gt; li:nth-child(5) &gt; [class="text-sm\ font-medium\ px-2\ py-2\.5\ rounded-xl\ block\ btn\ btn-flat\ focus-visible\:bg-gray-100\ dark\:focus-visible\:bg-zinc-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'NFT')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>NFT</value>
        <webElementGuid>2ae91daf-dd54-41c1-aad8-732a5b0215a2</webElementGuid>
    </webElementProperties>
</WebElementEntity>