<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7fac9469-2e46-4a60-9e52-ac538f0e0776</elementGuidId>
    <imagePath></imagePath>
    <name>header_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/sticky-header[1]/header[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.header</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'header header--middle-left header--mobile-center page-width header--has-menu header--has-account')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header header--middle-left header--mobile-center page-width header--has-menu header--has-account</value>
        <webElementGuid>1499dc49-e0b8-4002-8a02-6cdd8c2620e2</webElementGuid>
    </webElementProperties>
</WebElementEntity>