<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a6bf4a3d-916a-4ef7-83c2-f03e749febfd</elementGuidId>
    <imagePath></imagePath>
    <name>header_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/sticky-header[1]/header[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.header</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'header header--middle-left header--mobile-center page-width header--has-menu header--has-account')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header header--middle-left header--mobile-center page-width header--has-menu header--has-account</value>
        <webElementGuid>7e63f726-c153-4215-8bdc-b6e67d5eba3b</webElementGuid>
    </webElementProperties>
</WebElementEntity>