<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fee1d1ae-0ff8-4c9e-8c4b-e3fcede8ebff</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_headermenu_home</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/sticky-header[1]/header[1]/nav[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#HeaderMenu-home</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'HeaderMenu-home') and equals(@class,'header__menu-item list-menu__item link link--text focus-inset')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header__menu-item list-menu__item link link--text focus-inset</value>
        <webElementGuid>5c037607-cf78-480e-b931-5d44d4f74376</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>HeaderMenu-home</value>
        <webElementGuid>711e78ab-e4dd-4e08-a280-860bc7371223</webElementGuid>
    </webElementProperties>
</WebElementEntity>