<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>83d64b7c-06b3-4953-a154-3b76cba22552</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_account_login</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/sticky-header[1]/header[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.header__icon--account</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'header__icon header__icon--account link focus-inset small-hide')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header__icon header__icon--account link focus-inset small-hide</value>
        <webElementGuid>37e5d552-30aa-4a9d-b2b2-0cd17abc2b6f</webElementGuid>
    </webElementProperties>
</WebElementEntity>