<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e384af47-636e-420d-8ad5-847768b7b642</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_headermenu_catalog</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/sticky-header[1]/header[1]/nav[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#HeaderMenu-catalog</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'HeaderMenu-catalog') and equals(@class,'header__menu-item list-menu__item link link--text focus-inset')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header__menu-item list-menu__item link link--text focus-inset</value>
        <webElementGuid>0e96aa6b-b2fc-4222-b128-2c68381c43a3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>HeaderMenu-catalog</value>
        <webElementGuid>ccc777d2-fed6-469c-a802-5fe4b5d51d30</webElementGuid>
    </webElementProperties>
</WebElementEntity>