<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1b2e260d-eb4a-403e-b20e-1cdd6fe57314</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_skl_skale</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[3]/span[1]/span[1]/table[1]/tbody[2]/tr[1]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\\ tableRow"]:nth-child(1) [class="focus-inset\\ styles_wrapper__hb1ig\\ tableCellSpacing"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'SKL\nSKALE')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Icon of SKALE SKL SKALE"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>SKL
        SKALE</value>
        <webElementGuid>ec36f228-9868-4904-8bb7-af1a709cffa8</webElementGuid>
    </webElementProperties>
</WebElementEntity>