<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7c43a2ab-7d99-47a1-8a07-9f0cf11c6e76</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_exchanges</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[3]/li[1]/ul[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="pl-8\ py-1\ pr-1"] &gt; li:nth-child(4) &gt; [class="text-sm\ font-medium\ px-2\ py-2\.5\ rounded-xl\ block\ btn\ btn-flat\ focus-visible\:bg-gray-100\ dark\:focus-visible\:bg-zinc-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Exchanges')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Exchanges</value>
        <webElementGuid>1c8d48b1-f913-4dd3-9309-9ea4cef740a7</webElementGuid>
    </webElementProperties>
</WebElementEntity>