<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>744cf469-93fe-4b56-9b3e-168fa7ff0898</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_op_optimism</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[3]/span[1]/span[1]/table[1]/tbody[2]/tr[1]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\ tableRow"]:nth-child(1) [class="focus-inset\ styles_wrapper__hb1ig\ tableCellSpacing"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'OP
            Optimism')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>OP
        Optimism</value>
        <webElementGuid>2ae91daf-dd54-41c1-aad8-732a5b0215a2</webElementGuid>
    </webElementProperties>
</WebElementEntity>