<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>66eae68c-6768-40b7-8de1-454d6a05eb43</elementGuidId>
    <imagePath></imagePath>
    <name>button_productsubmitbutton_template_1486710846269</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/div[6]/product-form[1]/form[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#ProductSubmitButton-template--14867108462697__main</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'ProductSubmitButton-template--14867108462697__main') and equals(@name,'add') and equals(@class,'product-form__submit button button--full-width button--secondary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>product-form__submit button button--full-width button--secondary</value>
        <webElementGuid>e4d64a9c-1461-4488-9d21-61f25742406a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ProductSubmitButton-template--14867108462697__main</value>
        <webElementGuid>0f21b2c6-f6f8-4e52-bd1b-c98610574ae9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add</value>
        <webElementGuid>3bb09127-e247-47cd-9487-32c65b14e8b0</webElementGuid>
    </webElementProperties>
</WebElementEntity>