<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5e6c06d6-1164-4edd-a82f-0b3842556595</elementGuidId>
    <imagePath></imagePath>
    <name>button_plus</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/div[5]/div[1]/quantity-input[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name='plus']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'plus') and equals(@class,'quantity__button no-js-hidden')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>quantity__button no-js-hidden</value>
        <webElementGuid>3328eb1b-b0fb-4b64-bc37-c60386137030</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>plus</value>
        <webElementGuid>8086a0b5-4eba-41fb-9387-aeca9168fa1d</webElementGuid>
    </webElementProperties>
</WebElementEntity>