<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4246c026-bf17-4363-a21c-311480883d99</elementGuidId>
    <imagePath></imagePath>
    <name>button_productsubmitbutton_template_1486710846269</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/div[6]/product-form[1]/form[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#ProductSubmitButton-template--14867108462697__main</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'ProductSubmitButton-template--14867108462697__main') and equals(@name,'add') and equals(@class,'product-form__submit button button--full-width button--secondary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>product-form__submit button button--full-width button--secondary</value>
        <webElementGuid>a61e87e6-76de-4d32-8b62-5a092b68c826</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ProductSubmitButton-template--14867108462697__main</value>
        <webElementGuid>35dd323d-8f48-4640-ba65-c48bab896910</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add</value>
        <webElementGuid>0350ab6c-cfb9-4888-9c2b-b83973595833</webElementGuid>
    </webElementProperties>
</WebElementEntity>