<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7042857d-c617-49a0-991c-853625ac7e9c</elementGuidId>
    <imagePath></imagePath>
    <name>button_plus</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/div[5]/div[1]/quantity-input[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name='plus']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'plus') and equals(@class,'quantity__button no-js-hidden')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>quantity__button no-js-hidden</value>
        <webElementGuid>067bdc94-81d9-4199-89c7-b88a96234e17</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>plus</value>
        <webElementGuid>deef4ac9-3dda-4136-9e1c-1895622665fc</webElementGuid>
    </webElementProperties>
</WebElementEntity>