<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>91526cea-4dff-409f-b06a-ddb259ac5070</elementGuidId>
    <imagePath></imagePath>
    <name>button_plus</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/div[5]/div[1]/quantity-input[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name='plus']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'plus') and equals(@class,'quantity__button no-js-hidden')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>quantity__button no-js-hidden</value>
        <webElementGuid>307831ff-ecaf-484c-9790-fb3f74dd8d43</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>plus</value>
        <webElementGuid>76018175-dba5-43b2-84e8-e03960085b3d</webElementGuid>
    </webElementProperties>
</WebElementEntity>