<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c1b46d4e-d5b8-46cc-916f-3567ea45a28d</elementGuidId>
    <imagePath></imagePath>
    <name>dd_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/cart-notification[1]/div[1]/div[1]/div[2]/div[2]/dl[1]/div[1]/dd[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>dd</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>