<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f17a5774-553d-4fd0-9fcb-41dd630a57ee</elementGuidId>
    <imagePath></imagePath>
    <name>div_cart_notification</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/cart-notification[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#cart-notification</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'cart-notification') and equals(@class,'cart-notification focus-inset color-background-1 gradient animate active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cart-notification focus-inset color-background-1 gradient animate active</value>
        <webElementGuid>2fc25d28-211b-49d7-b12c-69cbe05bfbb5</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>cart-notification</value>
        <webElementGuid>700a52dc-df7e-4ed8-96ae-5ebbbb8cec00</webElementGuid>
    </webElementProperties>
</WebElementEntity>