<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>315c0908-dc2c-4a73-bf65-11d5364271ad</elementGuidId>
    <imagePath></imagePath>
    <name>div_cart_notification</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/cart-notification[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#cart-notification</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'cart-notification') and equals(@class,'cart-notification focus-inset color-background-1 gradient animate active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cart-notification focus-inset color-background-1 gradient animate active</value>
        <webElementGuid>9fcf2a2f-86f2-4e4a-aa4b-3a79a0b6d8ed</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>cart-notification</value>
        <webElementGuid>1232a222-cad7-4b15-af6a-8d58ceecd367</webElementGuid>
    </webElementProperties>
</WebElementEntity>