<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1a9b4404-ed4a-45a8-8f9d-315d7ad04eca</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_cart_notification_button</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/cart-notification[1]/div[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#cart-notification-button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'cart-notification-button') and equals(@class,'button button--secondary button--full-width')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>button button--secondary button--full-width</value>
        <webElementGuid>28e7c823-6f91-40f3-b613-c1d1283d0e54</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>cart-notification-button</value>
        <webElementGuid>416cb945-d854-49fc-a8e4-f7c3516269d1</webElementGuid>
    </webElementProperties>
</WebElementEntity>