<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a3aad5b2-00f5-4882-ad5d-a0463e31533c</elementGuidId>
    <imagePath></imagePath>
    <name>p_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/p[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.product__text</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'product__text inline-richtext caption-with-letter-spacing')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>product__text inline-richtext caption-with-letter-spacing</value>
        <webElementGuid>556a3a28-eec4-4668-b68f-adc394e62d50</webElementGuid>
    </webElementProperties>
</WebElementEntity>