<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6d9ea5c6-9378-416f-82e0-4d85d5c3aaa5</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_potential_airdrop</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(3) &gt; [class="px-2\ py-2\.5\ rounded-xl\ justify-start\ items-center\ gap-2\ inline-flex\ w-full\ btn\ btn-flat\ text-gray-900\ dark\:text-white\ focus-visible\:bg-gray-100\ dark\:focus-visible\:bg-zinc-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'🪂
            Potential Airdrop')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>🪂
        Potential Airdrop</value>
        <webElementGuid>1c8d48b1-f913-4dd3-9309-9ea4cef740a7</webElementGuid>
    </webElementProperties>
</WebElementEntity>