<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0f20a8c8-e047-4e5b-acc4-a505e5f7bcc4</elementGuidId>
    <imagePath></imagePath>
    <name>button_currency_eur</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/div[3]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex\\ p-2\\ gap-2\\ w-full\\ items-center\\ hover\\:bg-gray-100\\ rounded-xl\\ transition-colors\\ dark\\:hover\\:bg-zinc-700"]:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Currency\nEUR')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Currency
        EUR</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
</WebElementEntity>