<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>df3609a3-23e7-43ca-9331-4cafa674cbe9</elementGuidId>
    <imagePath></imagePath>
    <name>button_currency_eur</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/div[3]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex\ p-2\ gap-2\ w-full\ items-center\ hover\:bg-gray-100\ rounded-xl\ transition-colors\ dark\:hover\:bg-zinc-700"]:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Currency
            EUR')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Currency
        EUR</value>
        <webElementGuid>1c8d48b1-f913-4dd3-9309-9ea4cef740a7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>1c8d48b1-f913-4dd3-9309-9ea4cef740a7</webElementGuid>
    </webElementProperties>
</WebElementEntity>