<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3f9270b8-40bf-422c-8c06-9a8a72b5971f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_token_unlocks</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[2]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(3) &gt; [class="group\ flex\ gap-2\ items-center\ p-2\ w-full\ rounded-xl\ btn\ btn-flat\ focus-visible\:bg-gray-100\ dark\:focus-visible\:bg-zinc-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Token Unlocks')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Token Unlocks</value>
        <webElementGuid>2ae91daf-dd54-41c1-aad8-732a5b0215a2</webElementGuid>
    </webElementProperties>
</WebElementEntity>