<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>39e0cecc-e542-4bd8-8198-83f4e25a562f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_headermenu_home</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/sticky-header[1]/header[1]/nav[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#HeaderMenu-home</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'HeaderMenu-home') and equals(@class,'header__menu-item list-menu__item link link--text focus-inset')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header__menu-item list-menu__item link link--text focus-inset</value>
        <webElementGuid>1162232d-6e89-4949-ab04-30b49d9df2d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>HeaderMenu-home</value>
        <webElementGuid>949d2e10-ea01-4649-8509-59e9e179b038</webElementGuid>
    </webElementProperties>
</WebElementEntity>