<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d09b41ce-6e84-49fb-b0a2-bbab960e8cea</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/sticky-header[1]/header[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.header__heading-link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'header__heading-link link link--text focus-inset')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header__heading-link link link--text focus-inset</value>
        <webElementGuid>e5193bff-259a-4e9f-8d78-bc648a91991a</webElementGuid>
    </webElementProperties>
</WebElementEntity>