<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c6c475a5-1f46-4576-b12a-e2f43efa112e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_headermenu_contact</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/sticky-header[1]/header[1]/nav[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#HeaderMenu-contact</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'HeaderMenu-contact') and equals(@class,'header__menu-item list-menu__item link link--text focus-inset')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header__menu-item list-menu__item link link--text focus-inset</value>
        <webElementGuid>35f4d6ef-dd9c-42e2-bcbf-546aa90803f2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>HeaderMenu-contact</value>
        <webElementGuid>20299dd2-61a7-4e66-a5be-89c9ecb8e9f1</webElementGuid>
    </webElementProperties>
</WebElementEntity>