<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cf626d59-164c-441a-b8a7-c768cd65d9ea</elementGuidId>
    <imagePath></imagePath>
    <name>input_username</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[2]/form[1]/div[3]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'username')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>username</value>
        <webElementGuid>6245185f-f777-4a68-ad87-c72c2a7396d0</webElementGuid>
    </webElementProperties>
</WebElementEntity>