<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enter a security code</name>
   <tag></tag>
   <elementGuidId>8762a6cb-ac44-419e-8325-ba9a4987408a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idA_SAASTO_TOTP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='idA_SAASTO_TOTP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f132d841-b877-46a4-994d-80241edab675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idA_SAASTO_TOTP</value>
      <webElementGuid>77278fdc-4d03-4e8f-b5ae-da9fbde3547b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>694687dd-cca3-4219-be59-a019104421e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter a security code</value>
      <webElementGuid>c35f23a8-af1e-4947-9492-736c4a92fbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idA_SAASTO_TOTP&quot;)</value>
      <webElementGuid>6750055a-1a79-4eeb-98a4-45198e5067ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='idA_SAASTO_TOTP']</value>
      <webElementGuid>79e1b3b1-8fdd-4998-ab02-253d7cb07c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idDiv_SAASTO_TOTP']/a</value>
      <webElementGuid>faf22f03-bf92-4b75-aa25-2a47f9f71b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enter a security code')]</value>
      <webElementGuid>8361e574-7616-46c1-a84f-42721cbfa9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Having trouble?'])[1]/following::a[1]</value>
      <webElementGuid>6a443692-9287-44a1-bd51-067e3fb18e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of use'])[1]/preceding::a[2]</value>
      <webElementGuid>a214e1bf-d9ae-4dcf-86e7-aee957f23a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter a security code']/parent::*</value>
      <webElementGuid>f0d8dff2-d9b2-42a0-a3d1-1f91f331f1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>00456db0-a4ed-4c83-accc-f43c28329706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>8f30c94a-52a0-4397-af17-b5c1e2593314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'idA_SAASTO_TOTP' and @href = '#' and (text() = 'Enter a security code' or . = 'Enter a security code')]</value>
      <webElementGuid>4c2f49a2-e63d-416c-9ca3-14a127578c96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
