<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_I cant use my Microsoft Authenticator app</name>
   <tag></tag>
   <elementGuidId>c6117072-43b7-45ad-92b1-89554d89da92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInAnotherWay</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='signInAnotherWay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7825b9d2-13ea-46f0-a833-19fbbdfa7ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4619f6cc-85ac-4184-8f84-fdd7d9baaa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInAnotherWay</value>
      <webElementGuid>b732349f-e612-4d35-92a3-492e75382666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>idDiv_SAOTCAS_Title idDiv_SAOTCAS_Description</value>
      <webElementGuid>179c4869-38d5-4736-9f95-a6091f086acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I can't use my Microsoft Authenticator app right now</value>
      <webElementGuid>cf54d3d4-3726-4597-a279-f69c2a8d7614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInAnotherWay&quot;)</value>
      <webElementGuid>b0195ad4-1e00-476a-ac37-c019339b50c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='signInAnotherWay']</value>
      <webElementGuid>07ed42e5-1ee8-490f-8010-e3c9a67a1d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idDiv_SAOTCS_HavingTrouble']/a</value>
      <webElementGuid>75ee8da3-2328-4bc3-83df-328cf5549f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('I sign in frequently on this device. Don', &quot;'&quot;, 't ask me to approve requests here.')])[1]/following::a[1]</value>
      <webElementGuid>4d9865b3-9efd-4084-8ed8-3cd4beee054d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve sign in request'])[1]/following::a[1]</value>
      <webElementGuid>d7be89e5-98c1-4846-93b3-306bca129dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of use'])[1]/preceding::a[1]</value>
      <webElementGuid>27bec8ba-75e6-4402-9a48-f1d01c559920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy &amp; cookies'])[1]/preceding::a[2]</value>
      <webElementGuid>202731af-f942-4e68-8dad-d93827336d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>1896d4df-3fe2-4b20-a91d-61c688fc389e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>8dfb8b06-1c4f-4df5-a58f-78a54e0b2463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'signInAnotherWay' and (text() = concat(&quot;I can&quot; , &quot;'&quot; , &quot;t use my Microsoft Authenticator app right now&quot;) or . = concat(&quot;I can&quot; , &quot;'&quot; , &quot;t use my Microsoft Authenticator app right now&quot;))]</value>
      <webElementGuid>90a99215-b1cb-42ee-948b-25572521bb3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
