<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter TOTP code</name>
   <tag></tag>
   <elementGuidId>29c8f1f4-ef1f-4010-b513-b07cfbbe6a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idTxtBx_SAOTCC_OTC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idTxtBx_SAOTCC_OTC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4296392f-6fee-4e7b-8ff4-177f394b34f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idTxtBx_SAOTCC_OTC</value>
      <webElementGuid>215cbf5f-72dc-4f39-af89-07657ab4a07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otc</value>
      <webElementGuid>de2cd036-27e5-4839-9df9-76b1f9966834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6cd7c3a7-9c67-4af4-b691-59e880985217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>9471c805-3571-40de-b922-f84047fde164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d6112bcd-20d9-47d3-992c-41699aed5cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7655441e-ab59-4ef1-a80f-72ee063d0bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                  attr: {
                      'maxlength': otcLength,
                      'aria-labelledby': 'idDiv_SAOTCC_Title',
                      'aria-describedby': 'idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC' },
                  css: { 'has-error': error },
                  textInput: otcInputTextbox.value,
                  ariaLabel: str['CT_SAOTCC_STR_OTC_TBHint'],
                  hasFocusEx: otcInputTextbox.focused,
                  placeholder: $placeholderText</value>
      <webElementGuid>9b00d081-691b-45e2-a211-449afa6583bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>89c2f5fa-8bcb-4c28-a7c3-a7f72de6220d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>idDiv_SAOTCC_Title</value>
      <webElementGuid>b956228e-8f8e-46c8-b4b4-9e79306b1618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC</value>
      <webElementGuid>27c1297d-1da9-4de5-bffc-6adbb0102249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>b6cd0699-d97b-4100-a482-103a9ae99222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>85eb98a5-5d95-44eb-9cf8-45cf8d20ca90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTxtBx_SAOTCC_OTC&quot;)</value>
      <webElementGuid>fb503f95-dfef-4b67-a9fd-c9ff10f364c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idTxtBx_SAOTCC_OTC']</value>
      <webElementGuid>61162cb6-1abf-4dfe-a316-ddc879c16308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idDiv_SAOTCC_OTC']/div/input</value>
      <webElementGuid>1f2ae84e-268e-46d7-9c30-bea8421ba3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8963b1c1-fc51-4a26-a0f3-e3ad5af90c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idTxtBx_SAOTCC_OTC' and @name = 'otc' and @type = 'tel' and @placeholder = 'Code']</value>
      <webElementGuid>58c444f6-c4b2-4190-8e20-15fbb642f715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
