<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f61127ba-d4dc-4bad-9f8a-714ba67c316a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_featured_round_eigenlayer_funds_raised</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="col-span-2\\ flex\\ justify-between\\ gap-1\\ rounded-xl\\ bg-slate-50\\ p-2\\ font-medium\\ transition-colors\\ duration-200\\ ease-in-out\\ hover\\:bg-slate-100\\ dark\\:bg-zinc-700\\/50\\ dark\\:hover\\:bg-zinc-700\\/100"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Featured Round\nEigenLayer\xa0\nFunds Raised\n\U0001f4b0$100.00\xa0M')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Featured Round
        EigenLayer 
        Funds Raised
        💰$100.00 M</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
</WebElementEntity>