<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cded20a8-9e37-4ccb-ab98-23f60f3bedc4</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_featured_round_eigenlayer_funds_raised</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="col-span-2\ flex\ justify-between\ gap-1\ rounded-xl\ bg-slate-50\ p-2\ font-medium\ transition-colors\ duration-200\ ease-in-out\ hover\:bg-slate-100\ dark\:bg-zinc-700\/50\ dark\:hover\:bg-zinc-700\/100"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Featured Round
            EigenLayer 
            Funds Raised
            💰$100.00 M')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Featured Round
        EigenLayer 
        Funds Raised
        💰$100.00 M</value>
        <webElementGuid>2ae91daf-dd54-41c1-aad8-732a5b0215a2</webElementGuid>
    </webElementProperties>
</WebElementEntity>