<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e0a86c5b-7e19-44da-a43b-ea0b48a4d9b4</elementGuidId>
    <imagePath></imagePath>
    <name>div_cart_notification</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/cart-notification[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#cart-notification</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'cart-notification') and equals(@class,'cart-notification focus-inset color-background-1 gradient animate active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cart-notification focus-inset color-background-1 gradient animate active</value>
        <webElementGuid>d2380a40-e385-4fc3-9634-b31cc35ef60e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>cart-notification</value>
        <webElementGuid>7baaf423-4837-4f4e-8ef6-76e2824e98b5</webElementGuid>
    </webElementProperties>
</WebElementEntity>