<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>107770c5-5c05-4ef5-a88b-1b5d98ac5632</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_cryptocurrencies</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class=""]:nth-child(1) &gt; li &gt; [class="group\ flex\ gap-2\ items-center\ p-2\ w-full\ rounded-xl\ btn\ btn-flat\ focus-visible\:bg-gray-100\ dark\:focus-visible\:bg-zinc-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Cryptocurrencies')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Cryptocurrencies</value>
        <webElementGuid>01aa9a6f-a3d1-417f-8096-032a9fcbf1aa</webElementGuid>
    </webElementProperties>
</WebElementEntity>