<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>47a4d259-2747-4edc-9d23-574fb08f5a9b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_trx_11_tron</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[4]/span[1]/span[1]/table[1]/tbody[2]/tr[11]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\ tableRow"]:nth-child(11) &gt; [class="text-left\ align-middle\ tableCell\ tableCellSticky\ styles_coinRank__3elQw"] &gt; [class="focus-inset\ styles_wrapper__hb1ig\ tableCellSpacing"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'TRX
            11
            TRON')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TRX
        11
        TRON</value>
        <webElementGuid>c3e9a72f-a461-4000-8112-6005055d39a5</webElementGuid>
    </webElementProperties>
</WebElementEntity>