<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9a812aa7-b116-4181-bf14-198c8c7ba3df</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_8_ada_cardano</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[3]/span[1]/span[1]/table[1]/tbody[2]/tr[8]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\ tableRow"]:nth-child(8) &gt; [class="text-left\ align-middle\ tableCell\ tableCellSticky\ styles_coinRank__3elQw"] &gt; [class="focus-inset\ styles_wrapper__hb1ig\ tableCellSpacing"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'8
            ADA
            Cardano')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>8
        ADA
        Cardano</value>
        <webElementGuid>2ae91daf-dd54-41c1-aad8-732a5b0215a2</webElementGuid>
    </webElementProperties>
</WebElementEntity>