<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a30277e1-639d-4b61-b701-08987ad2a1ef</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_customize_presets_item_custom_ynuu7_plrv</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#customize-presets-item-custom-YNUU7_plrV-kq_fEVMpb8-324102</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'customize-presets-item-custom-YNUU7_plrV-kq_fEVMpb8-324102') and equals(@text,'\U0001f465 Twitter Rank')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>customize-presets-item-custom-YNUU7_plrV-kq_fEVMpb8-324102</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>👥 Twitter Rank</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
</WebElementEntity>