<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7341e586-add9-4ea6-a342-2b56f2c189c6</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_8_ada_cardano</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[3]/span[1]/span[1]/table[1]/tbody[2]/tr[8]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\\ tableRow"]:nth-child(8) &gt; [class="text-left\\ align-middle\\ tableCell\\ tableCellSticky\\ styles_coinRank__3elQw"] &gt; [class="focus-inset\\ styles_wrapper__hb1ig\\ tableCellSpacing"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'8\nADA\nCardano')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Icon of Cardano ADA Cardano"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>8
        ADA
        Cardano</value>
        <webElementGuid>ec36f228-9868-4904-8bb7-af1a709cffa8</webElementGuid>
    </webElementProperties>
</WebElementEntity>