<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>34039077-7f6c-4984-9c3d-b9f5c141cb17</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_investors_vcs_new</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[2]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class=""]:nth-child(3) &gt; li:nth-child(1) &gt; [class="group\ flex\ gap-2\ items-center\ p-2\ w-full\ rounded-xl\ btn\ btn-flat\ focus-visible\:bg-gray-100\ dark\:focus-visible\:bg-zinc-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Investors &amp; VCs
            New')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Investors &amp; VCs
        New</value>
        <webElementGuid>01aa9a6f-a3d1-417f-8096-032a9fcbf1aa</webElementGuid>
    </webElementProperties>
</WebElementEntity>