<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d2a5ee83-f9ed-4eea-bc27-82ed3c360e58</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_customize_presets_item_custom_ynuu7_plrv</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#customize-presets-item-custom-YNUU7_plrV-kq_fEVMpb8-324102</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'customize-presets-item-custom-YNUU7_plrV-kq_fEVMpb8-324102') and equals(@text,'👥 Twitter Rank')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>customize-presets-item-custom-YNUU7_plrV-kq_fEVMpb8-324102</value>
        <webElementGuid>2ae91daf-dd54-41c1-aad8-732a5b0215a2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>👥 Twitter Rank</value>
        <webElementGuid>2ae91daf-dd54-41c1-aad8-732a5b0215a2</webElementGuid>
    </webElementProperties>
</WebElementEntity>