<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2d830d0c-6796-4e4b-b86d-e7681649c0db</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_investors_vcs_new</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[2]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class=""]:nth-child(3) &gt; li:nth-child(1) &gt; [class="group\\ flex\\ gap-2\\ items-center\\ p-2\\ w-full\\ rounded-xl\\ btn\\ btn-flat\\ focus-visible\\:bg-gray-100\\ dark\\:focus-visible\\:bg-zinc-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Investors &amp; VCs\nNew')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Investors &amp; VCs New"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Investors &amp; VCs
        New</value>
        <webElementGuid>b8736e98-9c4f-49ee-9ffc-366e65ef3ff0</webElementGuid>
    </webElementProperties>
</WebElementEntity>