<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7ee8a1e6-f03a-4c67-8369-3de6e0287cd4</elementGuidId>
    <imagePath></imagePath>
    <name>button_search</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/header[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="action\\ h-10\\ w-full\\ \\!cursor-text\\ rounded-xl\\ bg-gray-100\\ px-3\\ text-base\\ text-gray-400\\ dark\\:bg-zinc-700\\ dark\\:text-zinc-500"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Search\n/')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Search for Asset, ICO,"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Search
        /</value>
        <webElementGuid>ec36f228-9868-4904-8bb7-af1a709cffa8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>ec36f228-9868-4904-8bb7-af1a709cffa8</webElementGuid>
    </webElementProperties>
</WebElementEntity>