<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1f771d7a-945c-48bd-8566-102eb1bebdca</elementGuidId>
    <imagePath></imagePath>
    <name>button_productsubmitbutton_template_1486710846269</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/div[6]/product-form[1]/form[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#ProductSubmitButton-template--14867108462697__main</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'ProductSubmitButton-template--14867108462697__main') and equals(@name,'add') and equals(@class,'product-form__submit button button--full-width button--secondary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>product-form__submit button button--full-width button--secondary</value>
        <webElementGuid>c580c302-5c73-4f86-a2c8-b11f5875d41d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ProductSubmitButton-template--14867108462697__main</value>
        <webElementGuid>ef5d0b62-19ef-46f9-b07f-6e5b562232cf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add</value>
        <webElementGuid>4ce182d2-8022-40b7-98ba-e25bee6693a9</webElementGuid>
    </webElementProperties>
</WebElementEntity>