<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e903bf55-ab9b-43f2-ac5e-193eafcf83f6</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_account_login</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/sticky-header[1]/header[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.header__icon--account</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'header__icon header__icon--account link focus-inset small-hide')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header__icon header__icon--account link focus-inset small-hide</value>
        <webElementGuid>0f67ddb7-9042-4b8c-a8be-b77c5a5462a5</webElementGuid>
    </webElementProperties>
</WebElementEntity>