<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>df15f54c-31bc-4036-8c1e-01b42c61ce8d</elementGuidId>
    <imagePath></imagePath>
    <name>select_sortby</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[2]/div[1]/div[1]/aside[1]/div[1]/facet-filters-form[1]/form[1]/div[3]/div[1]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#SortBy</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'SortBy') and equals(@name,'sort_by') and equals(@class,'facet-filters__sort select__select caption-large')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>facet-filters__sort select__select caption-large</value>
        <webElementGuid>763afc5a-7f02-4238-9328-86b9b58e5bc7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>SortBy</value>
        <webElementGuid>b965490c-a4a9-46d7-be17-3f212c8f476b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>sort_by</value>
        <webElementGuid>f1a3c82c-8cd4-42e7-8d37-455d0c2026b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>