<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>80e2450b-aadb-47a8-bcc9-8a435b62033a</elementGuidId>
    <imagePath></imagePath>
    <name>button_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/article[1]/section[2]/div[1]/div[2]/ul[1]/li[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="mr-1\ last\:mr-0"]:nth-child(2) &gt; [class="btn\ btn-flat\ btn-small\ block\ min-w-\[32px\]\ \!px-1\ \!text-gray-900\ focus-visible\:\!text-blue-600\ dark\:\!text-white\ dark\:focus-visible\:\!text-blue-500"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'2')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>2</value>
        <webElementGuid>c3e9a72f-a461-4000-8112-6005055d39a5</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>c3e9a72f-a461-4000-8112-6005055d39a5</webElementGuid>
    </webElementProperties>
</WebElementEntity>