<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>93ed8e9b-70b5-4eb8-989f-24f609d4fc63</elementGuidId>
    <imagePath></imagePath>
    <name>button_plus</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/div[5]/div[1]/quantity-input[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name='plus']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'plus') and equals(@class,'quantity__button no-js-hidden')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>quantity__button no-js-hidden</value>
        <webElementGuid>089dc2b3-cf0a-4025-9e6a-9dce7d5f8a4e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>plus</value>
        <webElementGuid>173e1dd5-ca25-44d5-802a-ef3af8cdd4a1</webElementGuid>
    </webElementProperties>
</WebElementEntity>