<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7d4532b7-afbf-4ac4-b82e-f257fd56e20c</elementGuidId>
    <imagePath></imagePath>
    <name>button_productsubmitbutton_template_1486710846269</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/div[6]/product-form[1]/form[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#ProductSubmitButton-template--14867108462697__main</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'ProductSubmitButton-template--14867108462697__main') and equals(@name,'add') and equals(@class,'product-form__submit button button--full-width button--secondary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>product-form__submit button button--full-width button--secondary</value>
        <webElementGuid>fc15ee6c-031b-4bc4-9692-321dcb2cba6d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ProductSubmitButton-template--14867108462697__main</value>
        <webElementGuid>9372bb72-dab7-49bf-8bdb-986f81519376</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add</value>
        <webElementGuid>8ae49b17-09f3-4696-8a4a-dddca5c8e966</webElementGuid>
    </webElementProperties>
</WebElementEntity>