<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8f247507-d796-408a-85be-4b29258c306a</elementGuidId>
    <imagePath></imagePath>
    <name>div_cart_notification</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/cart-notification[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#cart-notification</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'cart-notification') and equals(@class,'cart-notification focus-inset color-background-1 gradient animate active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cart-notification focus-inset color-background-1 gradient animate active</value>
        <webElementGuid>bd69ffca-bf11-497a-bb2b-67ad38b2e339</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>cart-notification</value>
        <webElementGuid>0e754a8b-3f3b-4298-ba66-cc81a6881dd6</webElementGuid>
    </webElementProperties>
</WebElementEntity>