<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cfd946f6-d758-485a-a0fe-0d7883e6c0c4</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_headermenu_catalog</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/sticky-header[1]/header[1]/nav[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#HeaderMenu-catalog</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'HeaderMenu-catalog') and equals(@class,'header__menu-item list-menu__item link link--text focus-inset')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>header__menu-item list-menu__item link link--text focus-inset</value>
        <webElementGuid>4278b9cf-1dcb-48b5-b629-691d7ba43370</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>HeaderMenu-catalog</value>
        <webElementGuid>255ff6a2-301f-41b3-84af-2a943f12aac3</webElementGuid>
    </webElementProperties>
</WebElementEntity>