<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0638ffd5-ec55-4cb9-b716-4e40bb162cd5</elementGuidId>
    <imagePath></imagePath>
    <name>product_productinfo_template_14867108462697_main</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#ProductInfo-template--14867108462697__main</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'ProductInfo-template--14867108462697__main') and equals(@class,'product__info-container product__column-sticky')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>product__info-container product__column-sticky</value>
        <webElementGuid>1f6b191c-c1c7-4a96-a170-e694e441a498</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ProductInfo-template--14867108462697__main</value>
        <webElementGuid>95d30891-52f2-4468-9ccc-688cc512f5e7</webElementGuid>
    </webElementProperties>
</WebElementEntity>