<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2f02f3cd-316e-447b-8011-846696fbffa3</elementGuidId>
    <imagePath></imagePath>
    <name>product_productinfo_template_14867108462697_main</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#ProductInfo-template--14867108462697__main</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'ProductInfo-template--14867108462697__main') and equals(@class,'product__info-container product__column-sticky')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>product__info-container product__column-sticky</value>
        <webElementGuid>96b7d395-dbde-4e8b-89b7-a3d064ed7be8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ProductInfo-template--14867108462697__main</value>
        <webElementGuid>8f67baa9-77fb-49c1-916b-11dedaa44878</webElementGuid>
    </webElementProperties>
</WebElementEntity>