<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>11e98b80-2013-4f70-97a1-2ee6e1e2a109</elementGuidId>
    <imagePath></imagePath>
    <name>section_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/article[1]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/section[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex\\ gap-2\\ text-xs\\ w-full\\ hidden\\ xs\\:flex\\ flex-wrap\\ gap-y-2"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>