<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fb47888f-6dff-4001-b3c7-8aceddbc9af5</elementGuidId>
    <imagePath></imagePath>
    <name>button_protocol_development_unlocked_340_73_m_alt</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/article[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[2]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\\ space-y-4\\ rounded-2xl\\ shadow-md\\ hover\\:bg-gray-100\\ active\\:bg-gray-300\\/50\\ dark\\:bg-zinc-800\\ dark\\:shadow-black\\ dark\\:hover\\:bg-zinc-700\\ dark\\:active\\:bg-zinc-500\\/50"]:nth-child(4) &gt; [class="action\\ w-full\\ px-4\\ pt-4"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Protocol Development\nUnlocked\xa0\n340.73\xa0M\xa0ALT\n/\xa02.00\xa0B\xa0ALT\nValue Locked\n$796.35\xa0M')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Protocol Development Unlocked"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Protocol Development
        Unlocked 
        340.73 M ALT
        / 2.00 B ALT
        Value Locked
        $796.35 M</value>
        <webElementGuid>ec36f228-9868-4904-8bb7-af1a709cffa8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>ec36f228-9868-4904-8bb7-af1a709cffa8</webElementGuid>
    </webElementProperties>
</WebElementEntity>