<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>171b6d4f-4e10-4c1b-954b-0b6bff6999e2</elementGuidId>
    <imagePath></imagePath>
    <name>button_treasury_unlocked_51_57_m_alt_2_15_b_alt</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/article[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[2]/div[5]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\\ space-y-4\\ rounded-2xl\\ shadow-md\\ hover\\:bg-gray-100\\ active\\:bg-gray-300\\/50\\ dark\\:bg-zinc-800\\ dark\\:shadow-black\\ dark\\:hover\\:bg-zinc-700\\ dark\\:active\\:bg-zinc-500\\/50"]:nth-child(5) &gt; [class="action\\ w-full\\ px-4\\ pt-4"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Treasury\nUnlocked\xa0\n51.57\xa0M\xa0ALT\n/\xa02.15\xa0B\xa0ALT\nValue Locked\n$1.01\xa0B')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Treasury
        Unlocked 
        51.57 M ALT
        / 2.15 B ALT
        Value Locked
        $1.01 B</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
</WebElementEntity>