<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cc35f8a3-0ec1-44ba-86be-a2671a6a4761</elementGuidId>
    <imagePath></imagePath>
    <name>button_advisors_unlocked_0_alt_500_00_m_alt_val</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/article[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\\ space-y-4\\ rounded-2xl\\ shadow-md\\ hover\\:bg-gray-100\\ active\\:bg-gray-300\\/50\\ dark\\:bg-zinc-800\\ dark\\:shadow-black\\ dark\\:hover\\:bg-zinc-700\\ dark\\:active\\:bg-zinc-500\\/50"]:nth-child(1) &gt; [class="action\\ w-full\\ px-4\\ pt-4"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Advisors\nUnlocked\xa0\n0\xa0ALT\n/\xa0500.00\xa0M\xa0ALT\nValue Locked\n$241.80\xa0M')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Advisors
        Unlocked 
        0 ALT
        / 500.00 M ALT
        Value Locked
        $241.80 M</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
</WebElementEntity>