<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f7f17a79-fc12-4d02-a644-30c5c4def442</elementGuidId>
    <imagePath></imagePath>
    <name>button_team_unlocked_0_alt_1_50_b_alt_value_loc</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/article[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\\ space-y-4\\ rounded-2xl\\ shadow-md\\ hover\\:bg-gray-100\\ active\\:bg-gray-300\\/50\\ dark\\:bg-zinc-800\\ dark\\:shadow-black\\ dark\\:hover\\:bg-zinc-700\\ dark\\:active\\:bg-zinc-500\\/50"]:nth-child(2) &gt; [class="action\\ w-full\\ px-4\\ pt-4"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Team\nUnlocked\xa0\n0\xa0ALT\n/\xa01.50\xa0B\xa0ALT\nValue Locked\n$719.91\xa0M')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Team
        Unlocked 
        0 ALT
        / 1.50 B ALT
        Value Locked
        $719.91 M</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>0d1d0d99-92d8-4477-8086-720f1327817f</webElementGuid>
    </webElementProperties>
</WebElementEntity>