<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>31e74e87-e454-45d1-979b-22963691d343</elementGuidId>
    <imagePath></imagePath>
    <name>button_team_unlocked_0_alt_1_50_b_alt_value_loc</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/article[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\\ space-y-4\\ rounded-2xl\\ shadow-md\\ hover\\:bg-gray-100\\ active\\:bg-gray-300\\/50\\ dark\\:bg-zinc-800\\ dark\\:shadow-black\\ dark\\:hover\\:bg-zinc-700\\ dark\\:active\\:bg-zinc-500\\/50"]:nth-child(2) &gt; [class="action\\ w-full\\ px-4\\ pt-4"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Team\nUnlocked\xa0\n0\xa0ALT\n/\xa01.50\xa0B\xa0ALT\nValue Locked\n$719.91\xa0M')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Team Unlocked 0 ALT / 1.50 B"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Team
        Unlocked 
        0 ALT
        / 1.50 B ALT
        Value Locked
        $719.91 M</value>
        <webElementGuid>ec36f228-9868-4904-8bb7-af1a709cffa8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>ec36f228-9868-4904-8bb7-af1a709cffa8</webElementGuid>
    </webElementProperties>
</WebElementEntity>