<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>af2c7026-863f-4bfa-8a27-12596e3d3423</elementGuidId>
    <imagePath></imagePath>
    <name>button_plus</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/div[5]/div[1]/quantity-input[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name='plus']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'plus') and equals(@class,'quantity__button no-js-hidden')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>quantity__button no-js-hidden</value>
        <webElementGuid>9fe53b7e-221b-43b8-8db4-5f1a6213076c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>plus</value>
        <webElementGuid>391aae8b-92cc-407e-ae59-417951037532</webElementGuid>
    </webElementProperties>
</WebElementEntity>