<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2fcb92c0-9819-4d9a-885d-aa8be58e23fe</elementGuidId>
    <imagePath></imagePath>
    <name>button_productsubmitbutton_template_1486710846269</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/section[1]/div[1]/div[2]/product-info[1]/div[6]/product-form[1]/form[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#ProductSubmitButton-template--14867108462697__main</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'ProductSubmitButton-template--14867108462697__main') and equals(@name,'add') and equals(@class,'product-form__submit button button--full-width button--secondary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>product-form__submit button button--full-width button--secondary</value>
        <webElementGuid>4c4c9ceb-3cd1-43de-ac51-845ccefb198a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ProductSubmitButton-template--14867108462697__main</value>
        <webElementGuid>0a3fe4cc-f752-4ff2-91f9-731fe673053a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add</value>
        <webElementGuid>28de2df3-69ef-427c-997c-0ae54b4bd7db</webElementGuid>
    </webElementProperties>
</WebElementEntity>