<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>33ac399a-9b92-4d9d-87ce-aad6f9ba2862</elementGuidId>
    <imagePath></imagePath>
    <name>div_cart_notification</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/cart-notification[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#cart-notification</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'cart-notification') and equals(@class,'cart-notification focus-inset color-background-1 gradient animate active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cart-notification focus-inset color-background-1 gradient animate active</value>
        <webElementGuid>c74ad22c-a341-496f-8f34-827b5b73fc8d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>cart-notification</value>
        <webElementGuid>4af371d3-c256-4854-8844-52de871783c7</webElementGuid>
    </webElementProperties>
</WebElementEntity>