<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3bceb1d6-0a66-463b-baa2-5159eeda25a1</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_cart_notification_button</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/cart-notification[1]/div[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#cart-notification-button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'cart-notification-button') and equals(@class,'button button--secondary button--full-width')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>button button--secondary button--full-width</value>
        <webElementGuid>a4adddaa-61ac-4ff9-bd3c-17301be0bb8f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>cart-notification-button</value>
        <webElementGuid>bf29475f-3f72-493f-9428-70a61c9e825d</webElementGuid>
    </webElementProperties>
</WebElementEntity>