<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stay signed in</name>
   <tag></tag>
   <elementGuidId>d3ee38ee-74bf-4944-a5ea-037b0ec58026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.text-title</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lightbox']/div[3]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2962f6ef-5932-4401-93c5-83b43835663f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row text-title</value>
      <webElementGuid>ec480c1a-5b3d-4904-83d7-1618effc9e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>20d52c20-c7f3-4c5c-9543-3d9d8521c995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fea52b6e-516b-4917-b0ea-87bfabf818c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: str['STR_Kmsi_Title']</value>
      <webElementGuid>e79457ab-31af-409f-b1e2-f091b79bad40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stay signed in?</value>
      <webElementGuid>2ffd9c3d-e390-4154-b295-07bf84fe8c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lightbox&quot;)/div[3]/div[1]/div[@class=&quot;pagination-view has-identity-banner animate slide-in-next&quot;]/div[1]/div[@class=&quot;row text-title&quot;]</value>
      <webElementGuid>0ace2af8-f7bb-478e-8dab-469d95dac7c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox']/div[3]/div/div[2]/div/div</value>
      <webElementGuid>5409b922-f7be-407b-a392-ad858a4d826c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='katalon-truetest@outlook.com'])[1]/following::div[3]</value>
      <webElementGuid>66610cb6-0a32-4a23-bda8-d971df002b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Stay signed in so you don', &quot;'&quot;, 't have to sign in again next time.')])[1]/preceding::div[1]</value>
      <webElementGuid>e12148dd-a0be-4843-8b22-e61474948a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Don', &quot;'&quot;, 't show this again')])[1]/preceding::div[3]</value>
      <webElementGuid>5eaa16c1-3b84-45fe-83fd-db88aa7f553a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stay signed in?']/parent::*</value>
      <webElementGuid>c0f5c6f4-2f9e-4d2b-ad37-f86b2ef245bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>d5596148-6ed5-4aad-9e5a-64d30e1a949a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Stay signed in?' or . = 'Stay signed in?')]</value>
      <webElementGuid>e5c3fa76-3542-4e32-8248-674b17460ec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
