<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4bbf1538-d1d7-4547-acf7-da8669caf0ca</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_customize_presets_item_r3zkhbqevzhchqfcc</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#customize-presets-item-R3ZKHbqEVzhchqfCcH8EW-5448</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'customize-presets-item-R3ZKHbqEVzhchqfCcH8EW-5448') and equals(@text,'\u2705 Sorted by FDV')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Selected Tab \u2705 Sorted by FDV"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>customize-presets-item-R3ZKHbqEVzhchqfCcH8EW-5448</value>
        <webElementGuid>ec36f228-9868-4904-8bb7-af1a709cffa8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>✅ Sorted by FDV</value>
        <webElementGuid>ec36f228-9868-4904-8bb7-af1a709cffa8</webElementGuid>
    </webElementProperties>
</WebElementEntity>