<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9dcca08b-793b-4f0e-a1eb-b05ba120a0fc</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_top_gainers</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(1) &gt; [class="px-2\ py-2\.5\ rounded-xl\ justify-start\ items-center\ gap-2\ inline-flex\ w-full\ btn\ btn-flat\ text-gray-900\ dark\:text-white\ focus-visible\:bg-gray-100\ dark\:focus-visible\:bg-zinc-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'🚀
            Top Gainers')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>🚀
        Top Gainers</value>
        <webElementGuid>2ae91daf-dd54-41c1-aad8-732a5b0215a2</webElementGuid>
    </webElementProperties>
</WebElementEntity>