<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a36d0a63-7fa8-4372-893e-19c187c94d82</elementGuidId>
    <imagePath></imagePath>
    <name>button_market</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[3]/li[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class=""]:nth-child(1) &gt; [class="group\ flex\ gap-2\ items-center\ p-2\ w-full\ rounded-xl\ focus-inset\ btn\ btn-flat\ focus-visible\:bg-gray-100\ dark\:focus-visible\:bg-zinc-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Market')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Market</value>
        <webElementGuid>2ae91daf-dd54-41c1-aad8-732a5b0215a2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>2ae91daf-dd54-41c1-aad8-732a5b0215a2</webElementGuid>
    </webElementProperties>
</WebElementEntity>