<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>70506819-529f-4355-a596-152055a7ae10</elementGuidId>
    <imagePath></imagePath>
    <name>button_search</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/header[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="action\ h-10\ w-full\ \!cursor-text\ rounded-xl\ bg-gray-100\ px-3\ text-base\ text-gray-400\ dark\:bg-zinc-700\ dark\:text-zinc-500"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Search
            /')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Search
        /</value>
        <webElementGuid>c3e9a72f-a461-4000-8112-6005055d39a5</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>c3e9a72f-a461-4000-8112-6005055d39a5</webElementGuid>
    </webElementProperties>
</WebElementEntity>