<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>798261a8-9b5e-4cb5-8ed9-8135521f8127</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_binance_labs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/section[1]/span[1]/span[1]/table[1]/tbody[2]/tr[3]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\ tableRow"]:nth-child(3) [class="focus-inset\ inline-block\ h-full\ w-full\ tableCellSpacing"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Binance Labs')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Binance Labs</value>
        <webElementGuid>c3e9a72f-a461-4000-8112-6005055d39a5</webElementGuid>
    </webElementProperties>
</WebElementEntity>