<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>95a5b334-ba7a-4f4b-9ee1-af9d77cbc822</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_global_search_items_coin_58832</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#global-search-items-coin-58832</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'global-search-items-coin-58832') and equals(@text,'ALT
            134
            
            AltLayer
            
            $0.4446
            -5.52%')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>global-search-items-coin-58832</value>
        <webElementGuid>01aa9a6f-a3d1-417f-8096-032a9fcbf1aa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>ALT
        134
        
        AltLayer
        
        $0.4446
        -5.52%</value>
        <webElementGuid>01aa9a6f-a3d1-417f-8096-032a9fcbf1aa</webElementGuid>
    </webElementProperties>
</WebElementEntity>