<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e072c72e-04d2-4375-b281-7a76a159c7a4</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_binance_labs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/section[1]/span[1]/span[1]/table[1]/tbody[2]/tr[3]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\ tableRow"]:nth-child(3) [class="focus-inset\ inline-block\ h-full\ w-full\ tableCellSpacing"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Binance Labs')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Binance Labs</value>
        <webElementGuid>01aa9a6f-a3d1-417f-8096-032a9fcbf1aa</webElementGuid>
    </webElementProperties>
</WebElementEntity>