<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5fb13e9c-5ac7-4ccb-a5ab-a8f2747111c0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_a16z_andreessen_horowitz</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/section[1]/span[1]/span[1]/table[1]/tbody[2]/tr[1]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="group\ tableRow"]:nth-child(1) [class="focus-inset\ inline-block\ h-full\ w-full\ tableCellSpacing"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'a16z (Andreessen Horowitz)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>a16z (Andreessen Horowitz)</value>
        <webElementGuid>01aa9a6f-a3d1-417f-8096-032a9fcbf1aa</webElementGuid>
    </webElementProperties>
</WebElementEntity>